[package]
name = "http_get"
version = "0.1.0"
description = "Demo for registry package http (libcurl)"
author = "Flow Contributors"
license = "MIT"
entry = "src/main.flow"

[dependencies]
http = "0.1.0"

[dev-dependencies]
