// Auto-generated by scripts/gen_abi_bindings.py. Do not edit by hand.
#ifndef RENDERER_H
#define RENDERER_H

#include <stdint.h>
#include <stdbool.h>

#ifdef __cplusplus
extern "C" {
#endif

int32_t flow_vk_2048_init(int32_t width, int32_t height, const char* title, int32_t capacity);
void flow_vk_2048_shutdown(void);
int32_t flow_vk_2048_should_close(void);
void flow_vk_2048_poll(void);
int32_t flow_vk_2048_key_down(int32_t key);
void flow_vk_2048_draw(const float* instance_data, int32_t count);
void flow_vk_2048_upload_texture(const uint8_t* pixels, int32_t width, int32_t height);
int32_t flow_vk_begin_frame(void);
void flow_vk_end_frame(void);
int32_t flow_vk_create_instance_buffer(int32_t capacity);
void flow_vk_update_instance_buffer(int32_t buf, const float* instance_data, int32_t count);
void flow_vk_draw_instance_buffer(int32_t buf, int32_t count);
int32_t flow_vk_create_texture(int32_t width, int32_t height);
void flow_vk_update_texture(int32_t tex, const uint8_t* pixels, int32_t width, int32_t height);
void flow_vk_upload_mesh(const float* vertices, int32_t vertex_count, const uint16_t* indices, int32_t index_count);
void flow_vk_set_clear_color(float r, float g, float b);
void flow_vk_set_camera(float distance, float pitch, float yaw);
void flow_vk_set_viewport(int32_t width, int32_t height);

#ifdef __cplusplus
}
#endif

#endif // RENDERER_H
