#!/usr/bin/env python3
import argparse
import re
from pathlib import Path


TYPE_MAP_C = {
    "i32": "int32_t",
    "u8": "uint8_t",
    "f32": "float",
    "f64": "double",
    "bool": "bool",
    "string": "const char*",
    "void": "void",
}

TYPE_MAP_FLOW = {
    "i32": "i32",
    "u8": "u8",
    "f32": "f32",
    "f64": "f64",
    "bool": "i32",
    "string": "string",
    "void": "void",
}


def parse_type(raw: str):
    raw = raw.strip()
    is_const_ptr = False
    if raw.startswith("cptr<") and raw.endswith(">"):
        is_const_ptr = True
        inner = raw[5:-1].strip()
        return ("ptr", inner, is_const_ptr)
    if raw.startswith("ptr<") and raw.endswith(">"):
        inner = raw[4:-1].strip()
        return ("ptr", inner, is_const_ptr)
    return ("base", raw, is_const_ptr)


def c_type(typ: str):
    kind, inner, is_const_ptr = parse_type(typ)
    if kind == "ptr":
        base = TYPE_MAP_C.get(inner, inner)
        const_prefix = "const " if is_const_ptr else ""
        return f"{const_prefix}{base}*"
    return TYPE_MAP_C.get(inner, inner)


def flow_type(typ: str):
    kind, inner, _ = parse_type(typ)
    if kind == "ptr":
        return f"ptr<{TYPE_MAP_FLOW.get(inner, inner)}>"
    return TYPE_MAP_FLOW.get(inner, inner)


def parse_signature(line: str):
    m = re.match(r"fn\s+([A-Za-z_][A-Za-z0-9_]*)\s*\((.*)\)\s*->\s*([^\s]+)\s*$", line)
    if not m:
        return None
    name = m.group(1)
    args_raw = m.group(2).strip()
    ret_raw = m.group(3).strip()
    args = []
    if args_raw:
        for part in args_raw.split(","):
            part = part.strip()
            if not part:
                continue
            name_type = part.split(":")
            if len(name_type) != 2:
                raise ValueError(f"Invalid arg: {part}")
            arg_name = name_type[0].strip()
            arg_type = name_type[1].strip()
            args.append((arg_name, arg_type))
    return name, args, ret_raw


def generate_c_header(signatures, header_name: str):
    lines = []
    guard = header_name.upper().replace(".", "_")
    lines.append("// Auto-generated by scripts/gen_abi_bindings.py. Do not edit by hand.")
    lines.append(f"#ifndef {guard}")
    lines.append(f"#define {guard}")
    lines.append("")
    lines.append("#include <stdint.h>")
    lines.append("#include <stdbool.h>")
    lines.append("")
    lines.append("#ifdef __cplusplus")
    lines.append('extern "C" {')
    lines.append("#endif")
    lines.append("")
    for name, args, ret in signatures:
        ret_c = c_type(ret)
        arg_list = []
        for arg_name, arg_type in args:
            arg_list.append(f"{c_type(arg_type)} {arg_name}")
        args_c = ", ".join(arg_list) if arg_list else "void"
        lines.append(f"{ret_c} {name}({args_c});")
    lines.append("")
    lines.append("#ifdef __cplusplus")
    lines.append("}")
    lines.append("#endif")
    lines.append("")
    lines.append(f"#endif // {guard}")
    return "\n".join(lines) + "\n"


def generate_flow_bindings(signatures):
    lines = []
    lines.append("# Auto-generated by scripts/gen_abi_bindings.py. Do not edit by hand.")
    lines.append("extern {")
    for name, args, ret in signatures:
        args_flow = ", ".join([f"{arg_name}: {flow_type(arg_type)}" for arg_name, arg_type in args])
        ret_flow = flow_type(ret)
        lines.append(f"    function {name}({args_flow}) -> {ret_flow}")
    lines.append("}")
    lines.append("")
    return "\n".join(lines)


def main():
    parser = argparse.ArgumentParser(description="Generate C and Flow bindings from a .abi file.")
    parser.add_argument("abi_file", help="Path to .abi file")
    parser.add_argument("--out-dir", default=None, help="Output directory (defaults to ABI file directory)")
    args = parser.parse_args()

    abi_path = Path(args.abi_file)
    if not abi_path.exists():
        raise SystemExit(f"ABI file not found: {abi_path}")

    out_dir = Path(args.out_dir) if args.out_dir else abi_path.parent
    out_dir.mkdir(parents=True, exist_ok=True)

    signatures = []
    for raw in abi_path.read_text().splitlines():
        line = raw.strip()
        if not line or line.startswith("#"):
            continue
        sig = parse_signature(line)
        if not sig:
            raise SystemExit(f"Invalid ABI line: {raw}")
        signatures.append(sig)

    header_name = abi_path.with_suffix(".h").name
    flow_name = abi_path.with_suffix(".flow").name

    (out_dir / header_name).write_text(generate_c_header(signatures, header_name))
    (out_dir / flow_name).write_text(generate_flow_bindings(signatures))


if __name__ == "__main__":
    main()
