// Auto-generated by scripts/gen_abi_bindings.py. Do not edit by hand.
#ifndef VULKAN_RENDERER_H
#define VULKAN_RENDERER_H

#include <stdint.h>
#include <stdbool.h>

#ifdef __cplusplus
extern "C" {
#endif

int32_t flow_vulkan_basic_run(int32_t pretty, int32_t trace, int32_t validation, int32_t width, int32_t height, float clear_r, float clear_g, float clear_b, const char* title);
int32_t flow_vulkan_advanced_run(int32_t pretty, int32_t trace, int32_t validation, int32_t width, int32_t height, float clear_r, float clear_g, float clear_b, float rotation_speed, const char* title, const char* texture_path, const char* texture_path2, float camera_distance, float camera_pitch, float camera_yaw, float move_speed, float mouse_sensitivity, float camera_smoothing, float mesh1_r, float mesh1_g, float mesh1_b, float mesh2_r, float mesh2_g, float mesh2_b, int32_t instance_count);

#ifdef __cplusplus
}
#endif

#endif // VULKAN_RENDERER_H
